package lk.workbridge.marketplace.enums;

public enum WorkerJobRole {
    PLUMBER,

    PAINTER
,
            ELECTRICIAN,

    CARPENTER,

            MASON,

    GARDENER,

            CLEANER,

    MOVER,
    WELDER,
    TILE_INSTALLATION,
    CEILING_INSTALLATION,
    ALUMINIUM_FABRICATION,
    CONTRACTOR,
    GARDENING,
    LANDSCAPING,
    TREE_CUTTING,
    COCONUT_PLUCKING,
    PEST_CONTROL,
    AC_REPAIR,
    CCTV_INSTALLATION,
    SOLAR_PANEL_INSTALLATION,
    GENERAL_HANDYMAN,
    VEHICLE_REPAIR,
    HOUSE_MOVERS,
    TOOL_RENTAL,
    EQUIPMENT_RENTAL,
    SAND_SOIL_GRAVEL_SUPPLY,
    GULLY_BOWSER,
    CUSHION_WORKS,
    CURTAIN_INSTALLATION,
    CHAIR_WEAVING,
    HOUSE_DEMOLITION

}
